
for i in 0..100
   
   cmd("MARS1 REQ_HK")
   sleep(0.25)
   cmd("MARS1 REQ_ENV")
   sleep(0.25)
   cmd("MARS1 REQ_PWR")
   sleep(0.25)
   cmd("MARS1 REQ_IMU")
   sleep(0.25)
   cmd("MARS1 REQ_STAT")
   sleep(0.25)
   cmd("MARS2 REQ_HK")
   sleep(0.25)
   cmd("MARS2 REQ_ENV")
   sleep(0.25)
   cmd("MARS2 REQ_PWR")
   sleep(0.25)
   cmd("MARS2 REQ_IMU")
   sleep(0.25)
   cmd("MARS2 REQ_STAT")
   sleep(0.25)
   cmd("LINK REQ_HK")
   sleep(0.25)
   cmd("LINK REQ_ENV")
   sleep(0.25)
   cmd("LINK REQ_PWR")
   sleep(0.25)
   cmd("LINK REQ_IMU")
   sleep(0.25)
   cmd("LINK REQ_FLTR")
   sleep(0.25)
   cmd("LINK REQ_INIT")
   for ii in 0..5
      puts("sleep #{ii} sec" )
      sleep(1)  
   end
end